// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Murad.WebApi.Data;

namespace Murad.WebApi.Migrations
{
    [DbContext(typeof(ProductContext))]
    [Migration("20230205112658_AddData_and_fixWarn")]
    partial class AddData_and_fixWarn
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.12")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Murad.WebApi.Data.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Stock")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedTime = new DateTime(2023, 2, 2, 15, 26, 57, 311, DateTimeKind.Local).AddTicks(377),
                            ImageUrl = "https://amazoncomp.az/wp-content/uploads/2020/08/Lenovo-IdeaPad-L3-15IML05.jpg",
                            Name = "Lenovo Ideapad",
                            Price = 1750m,
                            Stock = 20
                        },
                        new
                        {
                            Id = 2,
                            CreatedTime = new DateTime(2023, 1, 3, 15, 26, 57, 311, DateTimeKind.Local).AddTicks(7933),
                            ImageUrl = "https://www.tradeinn.com/f/13796/137965389/oneplus-nord-8gb-128gb-6.44-smartphone.jpg",
                            Name = "OnePlus",
                            Price = 1450m,
                            Stock = 10
                        },
                        new
                        {
                            Id = 3,
                            CreatedTime = new DateTime(2022, 12, 12, 15, 26, 57, 311, DateTimeKind.Local).AddTicks(7948),
                            ImageUrl = "https://strgimgr.umico.az/sized/1680/258600-e3d5563b2275dac6f48948047bebb250.jpg",
                            Name = "Mibro Watch X1",
                            Price = 82m,
                            Stock = 25
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
